# Generated by Django 5.0.7 on 2024-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_person_country_person_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_key_id", models.CharField(max_length=20, unique=True)),
                ("secret_access_key", models.CharField(max_length=40)),
                ("storage_bucket_name", models.CharField(max_length=100)),
                ("s3_file_overwrite", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("N", "None")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/avatar.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
