# Generated by Django 5.0.7 on 2024-09-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_awsconfiguration_alter_person_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsconfiguration",
            name="default_file_storage",
            field=models.CharField(
                default="storages.backends.s3boto3.S3Boto3Storage", max_length=100
            ),
        ),
    ]
