# Generated by Django 5.0.7 on 2024-10-31 17:39

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_awsconfiguration_default_file_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsconfiguration",
            name="access_key_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="person",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/avatar.jpg",
                upload_to=authentication.models.profile_picture_path,
            ),
        ),
    ]
