# Generated by Django 4.2.4 on 2024-02-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
