# Generated by Django 4.2.4 on 2024-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_databaseconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databaseconfiguration',
            name='engine',
            field=models.CharField(max_length=100),
        ),
    ]
