# Generated by Django 4.2.4 on 2024-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0005_person_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
