# Generated by Django 5.0.3 on 2024-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0007_remove_person_profile_picture_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
